### ISSUE TITLE
Update docker hub with new version

### ISSUE THREAD

**Issue by matrixik** [avivace/iosevka-docker#16]
Hello, looks like last image on Docker Hub is 2 years old and is not working any more. New version with fixes would probably fix that.

Thank you for creating this tool, now I need to add patching with nerd fonts to my Iosevka build script.

**Comment by a-berg** [comment]
Just commenting so the maintainers will notice this issue! The tool is awesome but I'd like the fix to #10 (marked as close) to be up!

**Comment by avivace** [comment]
Welp, thanks for the pings. I'll update it today :D

**Comment by avivace** [comment]
@a-berg @matrixik the image was updated and I added a ci to do so on every push to the repository :D

**Comment by avivace** [comment]
Done in https://github.com/avivace/iosevka-docker/commit/c3c5bdbe1956d5125f1208b773e36ade1c90c5e1

**Comment by matrixik** [comment]
Great, thank you very much.
