### ISSUE TITLE
failed when compile v7.0.1

### ISSUE THREAD

**Issue by nobk** [avivace/iosevka-docker#8]
Compile https://github.com/be5invis/Iosevka version v7.0.1 failed.

**Comment by nobk** [comment]
In the end, I found that the issue was not caused by docker builder, but the `a = "double-storey"` in my customized configuration file. v7.0+ changed the name of `a = "double-storey"` glyph.

**Comment by avivace** [comment]
@nobk Great, thanks for reporting and updating the issue!
